build_task:

  matrix:
    - name: FreeBSD14
      freebsd_instance:
        image_family: freebsd-14-3
    - name: FreeBSD15
      freebsd_instance:
        image_family: freebsd-15-0-amd64-ufs

  env:
    CIRRUS_CLONE_SUBMODULES: true

    # libfmt is not used, flexemu comes with local fmt sources as a git
    # submodule. But it helps to detect if the wrong fmt header files are used.
  install_pkg_script:
    - pkg install -y sudo pkgconf libtool libfmt ncurses cmake ninja qt5-qmake qt5-buildtools qt5-core qt5-gui qt5-widgets qt5-x11extras qt5-printsupport qt5-concurrent

  context_script:
    - sysctl -a | egrep -i 'hw.machine|hw.model|hw.ncpu|threads_per_core'
    - clang --version
    - clang++ --version
    - cmake --version
    - whoami
    - echo CIRRUS_USER_PERMISSION=$CIRRUS_USER_PERMISSION

  setup_script:
    - pw groupadd -n user
    - pw useradd -n user -d /home/user -s /bin/sh -G user,wheel
    - mkdir -p /home/user
    - chown -R user:user /home/user
    - chown -R user:user .
    - sudo -u user mkdir bld

  configure_script: sudo -u user sh -c "cd bld; cmake .. -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=$HOME/usr -DCMAKE_INSTALL_SYSCONFDIR=$HOME/etc; ls -lRa >ls-lRa.txt"

  make_script: sudo -u user sh -c "cd bld; ninja"

  install_script: cd bld; ninja install

  test_script:
    - sudo -u user sh -ec "cd bld; ctest -V"
    - sudo -u user bld/bin/test_gccasm
    - sudo -u user ldd bld/bin/flexemu
    - sudo -u user ldd bld/bin/flexplorer
    - sudo -u user bld/bin/dsktool -V
    - sudo -u user bld/bin/mdcrtool -V
    - sudo -u user bld/bin/flex2hex -V
    - sudo -u user bld/bin/dsktool -l disks/games.dsk
    - sudo -u user bld/bin/dsktool -f new.dsk -S 80dsdd
    - sudo -u user bld/bin/dsktool -C disks/system.dsk -T new.dsk
    - sudo -u user bld/bin/dsktool -l new.dsk

  always:
    build_dir_list_artifacts:
      path: bld/ls-lRa.txt
      type: text/plain
    cmake_cache_artifacts:
      path: bld/CMakeCache.txt
      type: text/plain
    compile_commands_artifacts:
      path: bld/compile_commands.json
      type: application/json
    unittests_log_artifacts:
      path: bld/unittests.log
      type: text/plain
