freebsd_instance:
  image_family: freebsd-14-1

build_task:

  env:
    CIRRUS_CLONE_SUBMODULES: true

  context_script:
    - sysctl -a | egrep -i 'hw.machine|hw.model|hw.ncpu|threads_per_core'
    - clang --version
    - clang++ --version
  install_pkg_script:
    - pkg install -y libtool qt5-qmake qt5-buildtools qt5-core qt5-gui qt5-widgets qt5-x11extras qt5-printsupport
    - ls -l /usr/local/lib/qt5/libQt5Core.so*

  configure_script: ./configure --prefix=$HOME/usr --sysconfdir=$HOME/etc

  make_script: make -j4

  install_script: make install

  test_script:
    - ldd src/flexemu
    - ldd src/flexplorer
    - make -j4 check
    - test/test_gccasm
    - src/dsktool -V
    - src/mdcrtool -V
    - src/flex2hex -V
    - src/dsktool -l disks/games.dsk
    - src/dsktool -f new.dsk -S 80dsdd
    - src/dsktool -C disks/system.dsk -T new.dsk
    - src/dsktool -l new.dsk

  always:
    config_log_artifacts:
      path: config.log
      type: text/plain
    unittest_log_artifacts:
      path: test/unittests.log
      type: text/plain
