freebsd_instance:
  image_family: freebsd-14-1

build_task:

  env:
    CIRRUS_CLONE_SUBMODULES: true

  context_script:
    - sysctl -a | egrep -i 'hw.machine|hw.model|hw.ncpu|threads_per_core'
    - clang --version
    - clang++ --version
    - whoami
    - echo CIRRUS_USER_PERMISSION=$CIRRUS_USER_PERMISSION

  install_pkg_script:
    - pkg install -y sudo pkgconf libtool ncurses qt5-qmake qt5-buildtools qt5-core qt5-gui qt5-widgets qt5-x11extras qt5-printsupport

  setup_script:
    - pw groupadd -n user
    - pw useradd -n user -d /home/user -s /bin/sh -G user,wheel
    - mkdir -p /home/user
    - chown -R user:user /home/user
    - chown -R user:user .

  configure_script: sudo -u user ./configure --prefix=$HOME/usr --sysconfdir=$HOME/etc

  make_script: sudo -u user make -j4

  install_script: make install

  test_script:
    - sudo -u user ldd src/flexemu
    - sudo -u user ldd src/flexplorer
    - sudo -u user make -j4 check
    - sudo -u user test/test_gccasm
    - sudo -u user src/dsktool -V
    - sudo -u user src/mdcrtool -V
    - sudo -u user src/flex2hex -V
    - sudo -u user src/dsktool -l disks/games.dsk
    - sudo -u user src/dsktool -f new.dsk -S 80dsdd
    - sudo -u user src/dsktool -C disks/system.dsk -T new.dsk
    - sudo -u user src/dsktool -l new.dsk

  always:
    config_log_artifacts:
      path: config.log
      type: text/plain
    unittest_log_artifacts:
      path: test/unittests.log
      type: text/plain
