version: 2.1

jobs:
  build-and-test:
    macos:
      xcode: "15.2.0"
    resource_class: "macos.m1.medium.gen1"
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - run:
          name: Install packages
          command: |
            brew install gnu-sed qt@5
            echo export PATH=/usr/local/opt/gnu-sed/libexec/gnubin:\$PATH >> $HOME/.bash_profile
            echo export PATH=/usr/local/opt/qt@5/bin:\$PATH >> $HOME/.bash_profile
      - run:
          name: Context
          command: |
            CCVER='/[^0-9]([0-9]+\.[0-9]+\.[0-9]+)/p;q'
            uname -a
            sysctl hw.physicalcpu
            sysctl hw.logicalcpu
            VER=`gcc --version | sed -nE $CCVER`
            echo "C compiler version:" $VER
            VER=`g++ --version | sed -nE $CCVER`
            echo "C++ compiler version:" $VER
      - run:
          name: Checkout
          command: |
            git clone https://github.com/aladur/flexemu.git
            cd flexemu
            git submodule update --init --recursive
      - run:
          name: Configure
          command: |
            cd flexemu
            ./configure --prefix=$HOME/usr --sysconfdir=$HOME/etc
      - run:
          name: Make
          command: cd flexemu; make -j8
      - run:
          name: Make install
          command: cd flexemu; make install
      - run:
          name: Test
          command: |
            cd flexemu
            make distcheck
            otool -L src/flexemu
            otool -L src/flexplorer
            make check
            src/test
            src/dsktool -l disks/games.dsk
            src/dsktool -f new.dsk -S 80dsdd
            src/dsktool -C disks/system.dsk -T new.dsk
            src/dsktool -l new.dsk

workflows:
  build-and-test-workflow:
    jobs:
      - build-and-test

