name: freebsd-build-and-test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: FreeBSD ${{ matrix.osversion }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        osversion: ['13.5', '14.4', '15.1']
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Run FreeBSD VM
        uses: vmactions/freebsd-vm@v1
        with:
          release: ${{ matrix.osversion }}
          usesh: true
          sync: rsync
          arch: x86_64
          mem: 6144
          # libfmt is not used, flexemu comes with local fmt sources as a git
          # submodule. But it helps to detect if the wrong fmt header files
          # are used.
          prepare: |
            echo "==== timestamp" `date`
            pkg update -f
            pkg install -y sudo pkgconf libtool libfmt ncurses cmake ninja
            pkg install -y qt5-qmake qt5-buildtools qt5-core qt5-gui qt5-widgets qt5-x11extras qt5-printsupport qt5-concurrent
            echo "==== timestamp" `date`

          run: |
            set -e
            mkdir -p result
            echo "=== System Information ==="
            echo "OS: " `uname -sr` > result/sys_info.txt
            sysctl -a | egrep -i 'hw.machine|hw.model|hw.ncpu|threads_per_core' >> result/sys_info.txt
            echo "whoami: " `whoami` >> result/sys_info.txt
            echo "pwd:" `pwd` >> result/sys_info.txt
            echo "SHELL: " $SHELL >> result/sys_info.txt
            echo "PATH: " $PATH >> result/sys_info.txt
            echo "==== VERSIONS ====" >> result/sys_info.txt
            cmake --version >> result/sys_info.txt
            echo "ninja version" `ninja --version` >> result/sys_info.txt
            clang --version >> result/sys_info.txt
            clang++ --version >> result/sys_info.txt
            echo "==== MANUALLY INSTALLED PACKAGES ====" >> result/sys_info.txt
            pkg prime-list >> result/sys_info.txt
            echo "==== END ====" >> result/sys_info.txt

            echo "=== Creating build user ==="
            pw groupadd -n user
            pw useradd -n user -d /home/user -s /bin/sh -G wheel
            mkdir -p /home/user
            chown -R user:user /home/user
            chown -R user:user .
            echo "passwd line for user: " `cat /etc/passwd | grep "^user:"` >>result/sys_info.txt

            echo "=== Configuring ==="
            sudo -u user sh -c '
              echo "==== timestamp" `date`
              mkdir -p bld
              cd bld
              cmake .. -G Ninja \
                -DCMAKE_INSTALL_PREFIX:PATH=$HOME/usr \
                -DCMAKE_INSTALL_SYSCONFDIR=$HOME/etc \
                -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
              ls -lRa > ls-lRa.txt
            '

            echo "=== Building ==="
            sudo -u user sh -c '
              cd bld
              echo "==== timestamp" `date`
              ninja'

            echo "=== Installing ==="
            sudo -u user sh -c '
              cd bld
              echo "==== timestamp" `date`
              ninja install'

            echo "=== Testing ==="
            sudo -u user sh -ec '
              cd bld
              echo "==== timestamp" `date`
              ctest -V --output-log unittests.log
            '

            echo "==== timestamp" `date`
            sudo -u user bld/bin/test_gccasm
            sudo -u user ldd bld/bin/flexemu
            sudo -u user ldd bld/bin/flexplorer

            for tool in dsktool mdcrtool flex2hex hex2flex; do
              sudo -u user bld/bin/$tool -V
            done

            sudo -u user bld/bin/dsktool -l disks/games.dsk
            sudo -u user bld/bin/dsktool -f new.dsk -S 80dsdd
            sudo -u user bld/bin/dsktool -C disks/system.dsk -T new.dsk
            sudo -u user bld/bin/dsktool -l new.dsk
            echo "==== timestamp" `date`

      - name: Upload build artefacts
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: freebsd-build-and-test-freebsd-${{ matrix.osversion }}-qt5-clang-results
          path: |
            result/sys_info.txt
            bld/ls-lRa.txt
            bld/CMakeCache.txt
            bld/compile_commands.json
            bld/unittests.log
